#page title
page_title                                : Smoke                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1482130530                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/smoke-for-steam/id1482130530?ls=1                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://getsmoke.app/assets/smoke-press-kit.zip                           
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : https://getsmoke.app/assets/appIcon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Smoke                                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Steam. Now on your wrist.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Archer Gardiner-Sheridan                                
your_link                                 :                     
your_city                                 : Adelaide                              
email_address                             : archergsdev@gmail.com
facebook_username                         :                                           
instagram_username                        : archergsdev
twitter_username                          : AppSmoke
github_username                           : archergs
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : View Your Account 
    description                           : View your account, including the games you've recently played, whether you're currently in-game and more
    fontawesome_icon_name                 : user-circle
    
  - title                                 : Find Your Friends
    description                           : See what your friend's accounts and the games they are playing
    fontawesome_icon_name                 : user-friends

  - title                                 : Game Library
    description                           : Access your whole game library, plus your playtime and achievements
    fontawesome_icon_name                 : gamepad

  - title                                 : Latest Gaming News
    description                           : Get up-to-date news articles for any game on Steam, and save them to read later
    fontawesome_icon_name                 : newspaper
    
  - title                                 : Access the Steam Store
    description                           : Browse the Steam store, view games and share them with friends
    fontawesome_icon_name                 : store
    
  - title                                 : Livestreams
    description                           : Watch any of the current top livestreams on Steam
    fontawesome_icon_name                 : tv

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/smoke.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
